# Generated by Django 5.0.3 on 2024-04-16 04:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolantProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('community_service', 'Community Service'), ('education_and_tutoring', 'Education and Tutoring'), ('healthcare_and_wellness', 'Healthcare and Wellness'), ('environmental_conservation', 'Environmental Conservation'), ('animal_welfare', 'Animal Welfare'), ('advocacy_and_human_rights', 'Advocacy and Human Rights'), ('arts_and_culture', 'Arts and Culture'), ('disaster_relief_and_emergency_response', 'Disaster Relief and Emergency Response'), ('technology_and_digital_skills', 'Technology and Digital Skills'), ('mentoring_and_youth_development', 'Mentoring and Youth Development'), ('international_volunteerism', 'International Volunteerism'), ('virtual_volunteering', 'Virtual Volunteering')], max_length=50)),
                ('project_objective', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('members_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VolantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_oppertunities.volantprojects')),
            ],
        ),
    ]
