# Generated by Django 5.0.3 on 2024-04-16 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_oppertunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volantdetails',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volantprojects',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='volantprojects',
            name='open_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volantprojects',
            name='project_objective',
            field=models.CharField(choices=[('service_and_support', 'Service and Support'), ('skill_development', 'Skill Development'), ('community_engagement', 'Community Engagement'), ('awareness_and_advocacy', 'Awareness and Advocacy'), ('capacity_building', 'Capacity Building'), ('empowerment', 'Empowerment'), ('cultural_exchange', 'Cultural Exchange'), ('personal_growth', 'Personal Growth and Fulfillment')], max_length=50),
        ),
    ]
