# Generated by Django 5.0.3 on 2024-04-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_oppertunities', '0002_alter_volantdetails_joined_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volantprojects',
            name='city',
            field=models.CharField(choices=[('colombo', 'Colombo'), ('gampaha', 'Gampaha'), ('kalutara', 'Kalutara'), ('kandy', 'Kandy'), ('matale', 'Matale'), ('nuwara_eliya', 'Nuwara Eliya'), ('galle', 'Galle'), ('matara', 'Matara'), ('hambantota', 'Hambantota'), ('jaffna', 'Jaffna'), ('mannar', 'Mannar'), ('vavuniya', 'Vavuniya'), ('mullaitivu', 'Mullaitivu'), ('kilinochchi', 'Kilinochchi'), ('batticaloa', 'Batticaloa'), ('ampara', 'Ampara'), ('trincomalee', 'Trincomalee'), ('kurunegala', 'Kurunegala'), ('puttalam', 'Puttalam'), ('anuradhapura', 'Anuradhapura'), ('polonnaruwa', 'Polonnaruwa'), ('badulla', 'Badulla'), ('moneragala', 'Moneragala'), ('ratnapura', 'Ratnapura'), ('kegalle', 'Kegalle')], default='colombo', max_length=50),
        ),
        migrations.AddField(
            model_name='volantprojects',
            name='region',
            field=models.CharField(choices=[('sabaragamuwa_province', 'Sabaragamuwa Province'), ('uva_province', 'Uva Province'), ('central_province', 'Central Province'), ('eastern_province', 'Eastern Province'), ('northern_province', 'Northern Province'), ('southern_province', 'Southern Province'), ('western_province', 'Western Province'), ('north_western_province', 'North Western Province'), ('north_central_province', 'North Central Province')], default='westren_province', max_length=50),
        ),
        migrations.AddField(
            model_name='volantprojects',
            name='status',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Incompleted')], default=False),
        ),
        migrations.AlterField(
            model_name='volantprojects',
            name='project_objective',
            field=models.CharField(choices=[('community_service', 'Community Service'), ('education_and_tutoring', 'Education and Tutoring'), ('healthcare_and_wellness', 'Healthcare and Wellness'), ('environmental_conservation', 'Environmental Conservation'), ('animal_welfare', 'Animal Welfare'), ('advocacy_and_human_rights', 'Advocacy and Human Rights'), ('arts_and_culture', 'Arts and Culture'), ('disaster_relief_and_emergency_response', 'Disaster Relief and Emergency Response'), ('technology_and_digital_skills', 'Technology and Digital Skills'), ('mentoring_and_youth_development', 'Mentoring and Youth Development'), ('international_volunteerism', 'International Volunteerism'), ('virtual_volunteering', 'Virtual Volunteering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='volantprojects',
            name='project_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('long_term', 'Long Term'), ('ongoin', 'Ongoing')], max_length=50),
        ),
    ]
